# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cf78d0b4709d2e07ac00d46e13bd2bca6ce58e76334e2354f9d1896583fac1a25d6aeaabcd1a2c34c371d6ab70dcd5890190d05b7e0cd174578df0adf4a5813

test:
  secret_key_base: 267b8ebd63ffebf079a84ba1da9621acb2c8d86ca4b5d5e9949cc8b64ee5a0cb8fabcbd8591c7e4fc95c07f77a8e6df4a6d2ab5524eda70523beba90dcc086bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
